apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: elasticsearch
        spanStartTimeShift: -1h
        spanEndTimeShift: 1h
        tags:
          - key: service.name
            value: service
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    uid: elasticsearch
    url: http://elasticsearch:9200
    database: "msbank-logs-*"
    editable: true
    jsonData:
      index: "msbank-logs-*"
      timeField: "@timestamp"
      esVersion: "8.13.4"
      logMessageField: message
      logLevelField: log.level
