apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}
  namespace: {{ include "svc.namespace" . }}
  labels:
    {{- include "svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "svc.selectorLabels" . | nindent 4 }}
