{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "svc.serviceAccountName" . }}
  namespace: {{ include "svc.namespace" . }}
  labels:
    {{- include "svc.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.workloadIdentityClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.global.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
