{{- if and .Values.global.keyVault .Values.global.keyVault.name -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "msbank.secretProviderClassName" . }}
  namespace: {{ include "msbank.namespace" . }}
  labels:
    {{- include "msbank.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    {{- if .Values.global.workloadIdentity.enabled }}
    clientID: {{ .Values.global.workloadIdentity.clientIds.apiGateway | quote }}
    {{- end }}
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    cloudName: "AzurePublicCloud"
    objects: |
      array:
      {{- range .Values.global.keyVault.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType | default "secret" }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion | quote }}
          {{- end }}
      {{- end }}
  secretObjects:
    - secretName: {{ include "msbank.fullname" . }}-kv-synced
      type: Opaque
      data:
      {{- range .Values.global.keyVault.objects }}
        - objectName: {{ .objectName }}
          key: {{ .envVar }}
      {{- end }}
{{- end -}}
